name: Generate and Publish Release Notes

on:
  workflow_dispatch:
    inputs:
      start_tag:
        description: 'Start Tag (e.g., v1.0.0)'
        required: true
      end_tag:
        description: 'End Tag (e.g., v1.0.6)'
        required: true

jobs:
  generate-and-publish-release-notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Release Notes
      id: generate-notes
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        configuration: |
          base: ${{ github.workspace }}/.github/changelog-config.json
        token: ${{ secrets.GITHUB_TOKEN }}
        startTag: ${{ github.event.inputs.start_tag }}
        endTag: ${{ github.event.inputs.end_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Confluence Page
      uses: knotel/confluence-content-update-action@v1
      with:
        base-url: ${{ secrets.CONFLUENCE_BASE_URL }}
        user: ${{ secrets.CONFLUENCE_USERNAME }}
        api-token: ${{ secrets.CONFLUENCE_API_TOKEN }}
        page-id: ${{ secrets.CONFLUENCE_PAGE_ID }}
        space-key: ${{ secrets.CONFLUENCE_SPACE_KEY }}
        parent-page-id: ${{ secrets.CONFLUENCE_PARENT_PAGE_ID }}
        title: "Release Notes ${{ github.event.inputs.start_tag }} to ${{ github.event.inputs.end_tag }}"
        content: |
          <ac:structured-macro ac:name="markdown">
            <ac:plain-text-body><![CDATA[
            # Release Notes from ${{ github.event.inputs.start_tag }} to ${{ github.event.inputs.end_tag }}
            
            ${{ steps.generate-notes.outputs.changelog }}
            ]]></ac:plain-text-body>
          </ac:structured-macro>
