name: Generate Release Notes

on:
  workflow_dispatch:
    inputs:
      start_tag:
        description: 'Start Tag (e.g., v1.0.0)'
        required: true
      end_tag:
        description: 'End Tag (e.g., v1.0.6)'
        required: true

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Release Notes
      id: generate-notes
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        configuration: |
          base: ${{ github.workspace }}/.github/changelog-config.json
        token: ${{ secrets.GITHUB_TOKEN }}
        startTag: ${{ github.event.inputs.start_tag }}
        endTag: ${{ github.event.inputs.end_tag }}

    - name: Create Release Notes File
      run: |
        echo "Release Notes between ${{ github.event.inputs.start_tag }} and ${{ github.event.inputs.end_tag }}"
        echo "${{ steps.generate-notes.outputs.changelog }}"
        echo "${{ steps.generate-notes.outputs.changelog }}" > release-notes.md

    - name: Show File Contents
      run: cat release-notes.md

    - name: Upload Release Notes
      uses: actions/upload-artifact@v3
      with:
        name: release-notes
        path: release-notes.md
