name: Generate and Publish Release Notes

on:
  workflow_dispatch:
    inputs:
      start_tag:
        description: 'Start Tag (e.g., v1.0.0)'
        required: true
      end_tag:
        description: 'End Tag (e.g., v1.0.6)'
        required: true

jobs:
  generate-and-publish-release-notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Release Notes
      id: generate-notes
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        configuration: |
          base: ${{ github.workspace }}/.github/changelog-config.json
        token: ${{ secrets.GITHUB_TOKEN }}
        startTag: ${{ github.event.inputs.start_tag }}
        endTag: ${{ github.event.inputs.end_tag }}

    - name: Update Confluence Page
      run: |
        # Convert markdown to Confluence Storage Format
        CONTENT=$(echo '${{ steps.generate-notes.outputs.changelog }}' | pandoc -f markdown -t html)

        # Create/Update Confluence page using REST API
        curl -u "${{ secrets.CONFLUENCE_EMAIL }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
          -X PUT \
          -H 'Content-Type: application/json' \
          --data-raw '{
            "id": "${{ secrets.CONFLUENCE_PAGE_ID }}",
            "type": "page",
            "title": "Release Notes ${{ github.event.inputs.start_tag }} to ${{ github.event.inputs.end_tag }}",
            "space": {"key": "${{ secrets.CONFLUENCE_SPACE_KEY }}"},
            "body": {
              "storage": {
                "value": "<p>Release notes between ${{ github.event.inputs.start_tag }} and ${{ github.event.inputs.end_tag }}</p>$CONTENT",
                "representation": "storage"
              }
            },
            "version": {"number": $(($(curl -s -u "${{ secrets.CONFLUENCE_EMAIL }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
              "https://${{ secrets.CONFLUENCE_BASE_URL }}/rest/api/content/${{ secrets.CONFLUENCE_PAGE_ID }}" | jq .version.number) + 1))}
          }' \
          "https://${{ secrets.CONFLUENCE_BASE_URL }}/rest/api/content/${{ secrets.CONFLUENCE_PAGE_ID }}"
      env:
        CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
