name: Generate Release Notes

on:
  workflow_dispatch:
    inputs:
      start_tag:
        description: 'Starting tag (e.g., v1.0.0)'
        required: true
      end_tag:
        description: 'Ending tag (e.g., v1.0.6)'
        required: true

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Release Notes
      uses: bobheadxi/generate-release-notes@v2
      with:
        config: .github/release-notes.toml
        output: release-notes.md
        fromTag: ${{ github.event.inputs.start_tag }}
        toTag: ${{ github.event.inputs.end_tag }}

    - name: Display Release Notes
      run: |
        echo "Generated release notes between ${{ github.event.inputs.start_tag }} and ${{ github.event.inputs.end_tag }}"
        cat release-notes.md
